### ISSUE TITLE
[ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by MasMedIm** [thnew/Pdf2Png#12]
```
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.unlink (fs.js:936:14)
    at C:\[DIR]\node_modules\pdf2png-mp2\lib\pdf2png.js:53:6
    at ChildProcess.exithandler (child_process.js:280:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

I can't currently use this library because of that problem. Is there any solution ?

Thank you !

**Comment by thnew** [comment]
Sorry for the late answer. I didn’t prepare the package for TypeScript yet, sorry
